# Generated by Django 4.0.2 on 2022-02-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aequitasjob_fairness_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aequitasjob',
            name='fairness_estimation',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
